# 컨테이너는 pod와 동일한 생명주기를 갖고 있어 pod가 사라지면 저장된 데이터도 다 사라진다.
# pod에서 돌리고 있는 것들의 데이터를 저장하고 싶다면 볼륨을 연결해야 한다.

apiVersion: vv1
kind: Pod
metadata:
  name: volume_connect
spec:
  containers:
  - name: nginx
    image: nginx
    
    volumeMounts:
    - volumeMountPath: /container-volume # 컨테이너 안에서 호스트의 볼륨과 연결될 경로
      name: my-volume # 밑에 나오는 볼륨 이름
  
  # 호스트에서 어느 경로와 볼륨을 연결할지 지정
  volumes:
  - name: my-volume
    hostPath:
      path: /home

# 컨테이너 안에서 volumeMountPath에 데이터를 저장하면 호스트의 /home 경로에 저장됨
